-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/BlueSpicePrivacy/maintenance/db/sql/bs_privacy_request.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/bs_privacy_request (
  pr_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pr_user INTEGER NOT NULL,
  pr_module VARCHAR(100) NOT NULL,
  pr_timestamp BLOB NOT NULL,
  pr_comment VARCHAR(255) DEFAULT NULL,
  pr_admin_comment VARCHAR(255) DEFAULT '',
  pr_status INTEGER DEFAULT 1 NOT NULL,
  pr_open INTEGER DEFAULT 1 NOT NULL,
  pr_data BLOB DEFAULT NULL
);
